// Walk No. 07 — two independent maps.
// Both read GeoJSON generated by ../pipeline/03_export.ipynb.
//
//   #far-map-lots — Day 14 map: every Bushwick tax lot as a dot, colored
//                    green -> red by unused FAR. Click for address,
//                    built/allowed FAR, and Street View.
//   #far-map-bg   — Day 18 map: block-group choropleth. Hover only, no click —
//                    just the average unused FAR per block group.

document.addEventListener('DOMContentLoaded', function () {
  initLotsMap();
  initBlockGroupMap();
});

function baseTiles() {
  return L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
    maxZoom: 19
  });
}

// Block-group choropleth ramp, low -> high unused FAR. Paper -> tape
// yellow -> ink, matching the site's existing brand palette.
function farColor(gap) {
  if (gap == null) return '#C9CBC2';
  if (gap < 0.5) return '#F1F2ED';
  if (gap < 1.0) return '#F2B63C';
  if (gap < 1.5) return '#D98A2B';
  if (gap < 2.5) return '#A8471F';
  return '#191C1A';
}

// Per-lot ramp, green (filling its allowed FAR) -> red (large unused gap).
// Breakpoints are the actual quartiles of far_gap across all Bushwick
// lots (0.33 / 0.78 / 1.2), so the 4 buckets are roughly evenly populated
// instead of split at arbitrary round numbers.
function lotColor(gap) {
  if (gap == null) return '#C9CBC2';
  if (gap < 0.33) return '#3A9D5D';
  if (gap < 0.78) return '#B5C93C';
  if (gap < 1.2) return '#E08A2B';
  return '#C0392B';
}

// PLUTO spells street suffixes out in full (AVENUE, STREET, ...). Typed
// search input usually doesn't, so expand common abbreviations before
// comparing. Keys must be pre-normalized (uppercase, no punctuation).
var STREET_ABBR = {
  ST: 'STREET', STR: 'STREET',
  AVE: 'AVENUE', AV: 'AVENUE',
  RD: 'ROAD',
  PL: 'PLACE',
  BLVD: 'BOULEVARD',
  DR: 'DRIVE',
  LN: 'LANE',
  CT: 'COURT',
  SQ: 'SQUARE',
  TER: 'TERRACE', TERR: 'TERRACE',
  PKWY: 'PARKWAY',
  HWY: 'HIGHWAY',
  EXPY: 'EXPRESSWAY'
};

function normalizeAddress(str) {
  return str
    .toUpperCase()
    .replace(/[.,#]/g, '')
    .trim()
    .split(/\s+/)
    .map(function (word) { return STREET_ABBR[word] || word; })
    .join(' ');
}

function initLotsMap() {
  var map = L.map('far-map-lots', {
    scrollWheelZoom: false,
    // 11,154 points as individual SVG DOM elements (Leaflet's default
    // renderer) is enough to make the layer silently never finish
    // painting. Canvas draws them all on one surface instead.
    renderer: L.canvas()
  }).setView([40.694, -73.920], 14);
  baseTiles().addTo(map);

  // normalized address -> circleMarker layer, built as lots load in.
  // Doubles as the source of truth for "is this a real Bushwick address":
  // anything not in here gets the invalid-address message.
  var addressIndex = {};

  // Attach the search form before the fetch resolves, not after — with
  // 11k features the load can take a moment, and a submit before the
  // listener exists would fall through to a native (page-reloading) GET.
  // initAddressSearch disables the input until this same addressIndex
  // object (mutated in place below) has entries.
  initAddressSearch(map, addressIndex);

  fetch('assets/bushwick_far_lots.geojson')
    .then(function (r) { return r.json(); })
    .then(function (data) {
      L.geoJSON(data, {
        pointToLayer: function (feature, latlng) {
          return L.circleMarker(latlng, {
            radius: 4,
            weight: 1,
            color: '#191C1A',
            fillColor: lotColor(feature.properties.far_gap),
            fillOpacity: 0.85
          });
        },
        onEachFeature: function (feature, layer) {
          // Popup content as a function, not a precomputed string: Leaflet
          // only calls this the moment a dot is actually clicked, instead
          // of building + storing an HTML string for all 11k lots upfront.
          layer.bindPopup(function () {
            var p = feature.properties;
            var lat = feature.geometry.coordinates[1];
            var lon = feature.geometry.coordinates[0];
            var streetViewUrl = 'https://maps.google.com/maps?q=&layer=c&cbll=' + lat + ',' + lon;

            return (
              '<b>' + p.address + '</b><br>' +
              'Built FAR: ' + p.builtfar.toFixed(2) + '<br>' +
              'Allowed FAR: ' + p.residfar.toFixed(2) + '<br>' +
              'Gap: ' + p.far_gap.toFixed(2) + '<br>' +
              '<a href="' + streetViewUrl + '" target="_blank" rel="noopener">Street View &rarr;</a>'
            );
          });

          // Only lots with a house number are real searchable addresses —
          // PLUTO also has unaddressed slivers (easements, ROW remnants)
          // that are just a street name.
          var addr = feature.properties.address;
          if (addr && /^\d/.test(addr)) {
            addressIndex[normalizeAddress(addr)] = layer;
          }
        }
      }).addTo(map);

      var input = document.getElementById('far-search-input');
      var button = document.querySelector('#far-search button');
      if (input) {
        input.disabled = false;
        input.placeholder = 'Search a Bushwick address (e.g. 441 Wilson Ave)';
      }
      if (button) button.disabled = false;
    })
    .catch(function (err) {
      console.error('Failed to load bushwick_far_lots.geojson:', err);
      var input = document.getElementById('far-search-input');
      if (input) input.placeholder = 'Search unavailable — lot data failed to load';
    });
}

function initAddressSearch(map, addressIndex) {
  var form = document.getElementById('far-search');
  var input = document.getElementById('far-search-input');
  var msg = document.getElementById('far-search-msg');
  if (!form) return;

  input.disabled = true;
  var button = form.querySelector('button');
  if (button) button.disabled = true;

  form.addEventListener('submit', function (e) {
    e.preventDefault();
    var query = input.value.trim();
    if (!query) return;

    var layer = addressIndex[normalizeAddress(query)];

    if (layer) {
      msg.hidden = true;
      map.flyTo(layer.getLatLng(), 18);
      layer.openPopup();
    } else {
      // textContent, not innerHTML — query is unsanitized user input.
      msg.textContent = 'No lot found for "' + query + '." Enter a valid Bushwick address, e.g. 441 Wilson Ave.';
      msg.hidden = false;
    }
  });
}

function initBlockGroupMap() {
  var map = L.map('far-map-bg', { scrollWheelZoom: false }).setView([40.694, -73.920], 14);
  baseTiles().addTo(map);

  fetch('assets/bushwick_far_gap.geojson')
    .then(function (r) { return r.json(); })
    .then(function (data) {
      L.geoJSON(data, {
        style: function (feature) {
          return {
            fillColor: farColor(feature.properties.far_gap),
            weight: 1,
            color: '#191C1A',
            opacity: 0.6,
            fillOpacity: 0.7
          };
        },
        // Hover-only: bindTooltip, not bindPopup — no click interaction on
        // this layer, just the average unused FAR for the block group.
        onEachFeature: function (feature, layer) {
          var p = feature.properties;
          layer.bindTooltip(
            'Avg unused FAR: ' + p.far_gap.toFixed(2) + ' &middot; ' + p.lot_count + ' lots',
            { sticky: true }
          );
        }
      }).addTo(map);
    })
    .catch(function (err) {
      console.error('Failed to load bushwick_far_gap.geojson:', err);
    });
}
