"""03 — Clean, join, and look.

Run:  python src/03_clean_join.py          (or: make clean_join)

Produces the three things Gate 2 needs:
  - data/processed/analysis_table.csv   one row per tract, model-ready
  - outputs/cleaning_log.md             every decision and the rows it cost
  - outputs/figures/scatter_rent_vs_walk.png   THE plot — log rent vs walk
    minutes with a lowess overlay. Look at it. This is the gate.
"""

from __future__ import annotations

import geopandas as gpd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm

import config as C
import lib


def main() -> None:
    tracts = gpd.read_file(C.PROCESSED / "band_tracts.geojson")
    walks = pd.read_csv(C.PROCESSED / "walk_times.csv", dtype={"GEOID": str})
    df = pd.DataFrame(tracts.drop(columns="geometry")).merge(
        walks, on="GEOID", how="left", validate="1:1"
    )

    clean, log = lib.clean_tracts(df)
    clean.to_csv(C.PROCESSED / "analysis_table.csv", index=False)

    # --- cleaning log, written as it happens, not reconstructed later ----
    lines = [
        "# Cleaning log — Walk No. 08",
        "",
        "Every dropped row is a modeling decision. This file is generated by",
        "`src/03_clean_join.py`; the rules live in `src/lib.py::clean_tracts`",
        "and `src/config.py`.",
        "",
        "| Decision | Tracts affected |",
        "|---|---|",
        *[f"| {desc} | {n} |" for desc, n in log],
        "",
        f"**Final analysis sample: {len(clean)} tracts.**",
    ]
    (C.ROOT / "outputs" / "cleaning_log.md").write_text("\n".join(lines))

    # --- the scatter ------------------------------------------------------
    d = clean.dropna(subset=["med_rent", "walk_L_min"])
    fig, ax = plt.subplots(figsize=(8, 5.5), dpi=150)
    ax.scatter(d.walk_L_min, d.med_rent, s=22, alpha=0.55, edgecolor="none")

    lo = sm.nonparametric.lowess(np.log(d.med_rent), d.walk_L_min, frac=0.5)
    ax.plot(lo[:, 0], np.exp(lo[:, 1]), lw=2.2)

    ax.set_yscale("log")
    ax.set_xlabel("Network walk time to nearest L station (min)")
    ax.set_ylabel("ACS median gross rent ($/mo, log scale)")
    vintage = int(d["acs_vintage"].iloc[0]) if "acs_vintage" in d else C.ACS_YEAR
    ax.set_title(f"Rent vs the walk to the L — {len(d)} tracts, "
                 f"ACS {vintage - 4}-{vintage} 5-year")
    ax.text(0.99, 0.02, "The Walkthrough NYC · Walk No. 08", transform=ax.transAxes,
            ha="right", va="bottom", fontsize=8, alpha=0.6)
    fig.tight_layout()
    out_png = C.FIGURES / "scatter_rent_vs_walk.png"
    fig.savefig(out_png)

    # --- Gate 2 aid: the bivariate slope, no controls ---------------------
    biv = sm.OLS(np.log(d.med_rent), sm.add_constant(d.walk_L_min)).fit()
    b = float(biv.params["walk_L_min"])

    print("Cleaning log -> outputs/cleaning_log.md")
    for desc, n in log:
        print(f"  - {desc}: {n}")
    print(f"\nAnalysis table -> data/processed/analysis_table.csv  ({len(clean)} tracts)")
    print(f"Scatter -> {out_png.relative_to(C.ROOT)}")

    print("\n" + "=" * 62)
    print(" GATE 2 — SIGNAL")
    print("=" * 62)
    print(f"  Bivariate slope (no controls): {b * 100:+.2f}% per walk minute")
    if b < 0:
        print(f"  Naive half-life at that slope: {lib.half_life(b):.0f} min")
    print("  Now OPEN THE SCATTER and look. The plot is the gate, not this")
    print("  number. No visible slope is still a piece — a better one.")
    print("=" * 62)


if __name__ == "__main__":
    main()
