"""03 — Clean, join, and look.

Run:  python src/03_clean_join.py          (or: make clean_join)

Runs the same clean + scatter step once per rent series: the combined
blended median and the three bedroom-specific cuts. Produces, per series:
  - data/processed/analysis_table[_Nbr].csv   one row per tract, model-ready
  - outputs/cleaning_log[_Nbr].md             every decision and the rows it cost
  - outputs/figures/scatter_rent_vs_ridgewood[_Nbr].png  THE plot — rent vs.
    walk to the nearest M-only (Ridgewood) station, 0-30 min, with a lowess
    overlay. Look at it. The plot is the gate, not the printed slope.
"""

from __future__ import annotations

import geopandas as gpd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.api as sm

import config as C
import lib

# One entry per rent series: (label, rent column, MOE column, output filename suffix)
SERIES = [
    ("combined (all bedrooms)", "med_rent", "med_rent_moe", ""),
    ("1BR", "med_rent_1br", "med_rent_1br_moe", "_1br"),
    ("2BR", "med_rent_2br", "med_rent_2br_moe", "_2br"),
    ("3BR", "med_rent_3br", "med_rent_3br_moe", "_3br"),
]

# One entry per chart: (x column, x-axis label, output filename stem)
CHARTS = [
    ("walk_M_min", "Network walk time to nearest M-only (Ridgewood) station (min)",
     "scatter_rent_vs_ridgewood"),
]


def make_scatter(d: pd.DataFrame, rent_col: str, x_col: str, x_label: str,
                  label: str, out_png) -> float:
    """One scatter + lowess + bivariate slope, restricted to the realistic
    0-30 min walking range — both the fit and the display, not just the
    display, so far-away tracts don't smooth out the local pattern.
    Returns the bivariate slope from that restricted range."""
    full_n = len(d)
    d = d[d[x_col] <= 30]

    fig, ax = plt.subplots(figsize=(8, 5.5), dpi=150)
    ax.scatter(d[x_col], d[rent_col], s=22, alpha=0.55, edgecolor="none")

    lo = sm.nonparametric.lowess(np.log(d[rent_col]), d[x_col], frac=0.3)
    ax.plot(lo[:, 0], np.exp(lo[:, 1]), lw=2.2)

    ax.set_yscale("log")
    ax.set_xlim(0, 30)
    ax.set_xlabel(x_label)
    ax.set_ylabel(f"ACS median gross rent, {label} ($/mo, log scale)")
    vintage = int(d["acs_vintage"].iloc[0]) if "acs_vintage" in d else C.ACS_YEAR
    ax.set_title(f"Rent vs. {x_label[0].lower()}{x_label[1:]} — {label}, "
                 f"{len(d)} of {full_n} tracts within 30 min, "
                 f"ACS {vintage - 4}-{vintage} 5-year")
    ax.text(0.99, 0.02, "The Walkthrough NYC · Walk No. 04", transform=ax.transAxes,
            ha="right", va="bottom", fontsize=8, alpha=0.6)
    fig.tight_layout()
    fig.savefig(out_png)
    plt.close(fig)

    biv = sm.OLS(np.log(d[rent_col]), sm.add_constant(d[x_col])).fit()
    return float(biv.params[x_col])


def process_series(df: pd.DataFrame, label: str, rent_col: str, moe_col: str, suffix: str) -> None:
    suffix = C.SPINE_TAG + suffix   # e.g. "_mspine_1br"; plain "_1br" for the L-spine run
    clean, log = lib.clean_tracts(df, rent_col=rent_col, moe_col=moe_col)
    clean.to_csv(C.PROCESSED / f"analysis_table{suffix}.csv", index=False)

    lines = [
        f"# Cleaning log — Walk No. 04 ({label})",
        "",
        "Every dropped row is a modeling decision. This file is generated by",
        "`src/03_clean_join.py`; the rules live in `src/lib.py::clean_tracts`",
        "and `src/config.py`.",
        "",
        "| Decision | Tracts affected |",
        "|---|---|",
        *[f"| {desc} | {n} |" for desc, n in log],
        "",
        f"**Final analysis sample: {len(clean)} tracts.**",
    ]
    (C.ROOT / "outputs" / f"cleaning_log{suffix}.md").write_text("\n".join(lines))

    print(f"\n--- {label} ---")
    print(f"Cleaning log -> outputs/cleaning_log{suffix}.md")
    for desc, n in log:
        print(f"  - {desc}: {n}")
    print(f"Analysis table -> data/processed/analysis_table{suffix}.csv  ({len(clean)} tracts)")

    for x_col, x_label, stem in CHARTS:
        d = clean.dropna(subset=[rent_col, x_col])
        out_png = C.FIGURES / f"{stem}{suffix}.png"
        b = make_scatter(d, rent_col, x_col, x_label, label, out_png)
        print(f"Scatter -> {out_png.relative_to(C.ROOT)}")
        print(f"  Bivariate slope (no controls): {b * 100:+.2f}% per walk minute")
        if b < 0:
            print(f"  Naive half-life at that slope: {lib.half_life(b):.0f} min")


def main() -> None:
    tracts = gpd.read_file(C.PROCESSED / f"band_tracts{C.SPINE_TAG}.geojson")
    walks = pd.read_csv(C.PROCESSED / f"walk_times{C.SPINE_TAG}.csv", dtype={"GEOID": str})
    df = pd.DataFrame(tracts.drop(columns="geometry")).merge(
        walks, on="GEOID", how="left", validate="1:1"
    )

    for label, rent_col, moe_col, suffix in SERIES:
        process_series(df, label, rent_col, moe_col, suffix)

    print("\n" + "=" * 62)
    print(" GATE 2 — SIGNAL (all four series, both charts)")
    print("=" * 62)
    print("  Now OPEN THE SCATTERS and look. The plots are the gate, not the")
    print("  printed slope. No visible slope is still a piece — a better one.")
    print("=" * 62)


if __name__ == "__main__":
    main()
